@isTest
public with sharing class RecordOwnerUtility_TEST {
    

    // getRandomUserByGroupOrQueue with cache

    // getRandomUserByGroupOrQueue without cache

    // getRandomUserByProfile with cache

    // getRandomUserByProfile without cache

    // getRandomUserByRole with cache

    // getRandomUserByRole without cache 

    // getUserByFullName with cache

    // getUserByFullName without cache 

    // getRandomUser invocable with cache

    // getRandomUser invocable without cache
}
